version: '3'

services:
  backend:
    container_name: FastAPI
    build: 
        context: .
        dockerfile: ./preBackend/fastAPI-Dockerfile
    restart: always
    volumes:
      - ./preBackend:/var/www/html
    ports:
      - 8000:8000
    tty: true

  # frontend:
  #   container_name: Nuxt
  #   image: node:14
  #   # build:
  #   #   context: .
  #   #   dockerfile: ./nginx/Frontend/Nuxt-Dockerfile
  #   #   # args:
  #   #   #   - WORKDIR=$WEB_WORKDIR
  #   #   #   - PORT=$WEB_PORT
  #   #   #   - CONTAINER_PORT=$WEB_CONTAINER_PORT
  #   #   #   - HOST=$HOST
  #   restart: always
  #   volumes:
  #     - ./nginx/Frontend:/var/www/html/Frontend
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - backend
  #   tty: true
  #   working_dir: /var/www/html/Frontend
  #   command: npm run dev
  nginx:
    build: 
      context: .
      dockerfile: ./nginx/nginx-Dockerfile
    ports:
        - "80:80"
    volumes:
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/Frontend:/var/www/html/Frontend
        - /var/www/html/Frontend/node_modules
    depends_on:
        - backend
  # db:
  #    image: {まだ決まってない}
  #    restart: always
  #    environment:
  #    ports:
  #    volumes:どこにマウントするか